[package]
name = "stepperfin-core"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
edition = "2018"
description = "Core functionality and abstractions for StepperFin 3D printer firmware."

[dependencies]
